// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBZXmqoEGYQuoTR-Lb2bE7hc1wDhLrx9Q',
    appId: '1:16901449939:web:b5d49614c0994be787cc26',
    messagingSenderId: '16901449939',
    projectId: 'chatapp-ceab2',
    authDomain: 'chatapp-ceab2.firebaseapp.com',
    storageBucket: 'chatapp-ceab2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqmyXrS5nZfv64nqBy2MYd72OLkEjyL2A',
    appId: '1:16901449939:ios:410593d24ac8a2b787cc26',
    messagingSenderId: '16901449939',
    projectId: 'chatapp-ceab2',
    storageBucket: 'chatapp-ceab2.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBZXmqoEGYQuoTR-Lb2bE7hc1wDhLrx9Q',
    appId: '1:16901449939:web:04fd63989986fe8287cc26',
    messagingSenderId: '16901449939',
    projectId: 'chatapp-ceab2',
    authDomain: 'chatapp-ceab2.firebaseapp.com',
    storageBucket: 'chatapp-ceab2.firebasestorage.app',
  );
}
